resource_types:
- name: git-multibranch
  type: docker-image
  source:
    repository: cfcommunity/git-multibranch-resource

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: test-application-develop
  type: git
  source:
    uri: git@github.com:sapiah/Test-Application.git
    branch: master
    private_key: ((github-private-key))

jobs:
- name: Unit Tests - Dev
  public: false
  plan:
  - get: test-application-develop
    trigger: true
  - task: Run Unit Tests Dev
    file: test-application-develop/ci/task_run_tests_dev.yml

- name: Build Dev
  public: false
  plan:
  - get: test-application-develop
    passed: [Unit Tests - Dev]
    trigger: true
  - task: Build Dev
    file: test-application-develop/ci/task_build_dev.yml